-- Run after migrations/0004_foundations.sql.
-- Latin-script languages (de, es, fr) get a "pronunciation guide" (sounds/spelling
-- rules that trip up new learners) since they don't have a separate alphabet to teach.
-- Script-based languages (hi, ja) get their actual core characters.

-- ===== Alphabet / pronunciation =====

insert into alphabet_characters (language, character, romanization, pronunciation_guide, example_word, example_translation, order_index) values
-- German
('de', 'ä', 'ae', 'Like "e" in "bed", fronted', 'Männer', 'men', 1),
('de', 'ö', 'oe', 'Like French "eu", round your lips saying "e"', 'schön', 'beautiful', 2),
('de', 'ü', 'ue', 'Like French "u", say "ee" with rounded lips', 'für', 'for', 3),
('de', 'ß', 'ss', 'Sharp "s" sound, never voiced like "z"', 'Straße', 'street', 4),
('de', 'ei', 'ai', 'Like "eye"', 'nein', 'no', 5),
('de', 'ie', 'ee', 'Long "ee" sound', 'sie', 'she/they', 6),
('de', 'sch', 'sh', 'Like English "sh"', 'schnell', 'fast', 7),
('de', 'ch', 'kh', 'Soft rasp at the back of the throat (after a,o,u) or front (after i,e)', 'ich', 'I', 8),
('de', 'w', 'v', 'Always pronounced like English "v"', 'wir', 'we', 9),
('de', 'z', 'ts', 'Always pronounced like "ts"', 'Zeit', 'time', 10),
-- Spanish
('es', 'a e i o u', '', 'Vowels are always short and pure — never diphthongized', 'casa', 'house', 1),
('es', 'll', 'y', 'Like English "y" in "yes" (varies by region)', 'llamar', 'to call', 2),
('es', 'ñ', 'ny', 'Like "ny" in "canyon"', 'año', 'year', 3),
('es', 'rr', 'rr', 'Strongly rolled/trilled r', 'perro', 'dog', 4),
('es', 'j', 'h', 'Harsh "h" sound from the throat', 'trabajo', 'work', 5),
('es', 'h', '', 'Always silent', 'hola', 'hello', 6),
('es', 'c (+e/i)', 'th/s', 'Soft "th" in Spain, "s" in Latin America', 'cielo', 'sky', 7),
('es', 'z', 'th/s', 'Soft "th" in Spain, "s" in Latin America', 'zapato', 'shoe', 8),
('es', 'v', 'b', 'Pronounced like a soft "b", not English "v"', 'vino', 'wine', 9),
('es', 'que/qui', 'ke/ki', '"u" is silent — hard "k" sound', 'queso', 'cheese', 10),
-- French
('fr', 'an/en', 'ah(n)', 'Nasal vowel — air through the nose, no hard "n"', 'enfant', 'child', 1),
('fr', 'in/un', 'a(n)', 'Nasal vowel, like "an" said through the nose', 'vin', 'wine', 2),
('fr', 'on', 'oh(n)', 'Nasal vowel — round lips, no hard "n"', 'bonjour', 'hello', 3),
('fr', 'u', 'ü', 'Say "ee" with rounded lips (different from "ou")', 'tu', 'you', 4),
('fr', 'ou', 'oo', 'Like English "oo" in "moon"', 'vous', 'you (formal)', 5),
('fr', 'r', '', 'Guttural, from the back of the throat', 'merci', 'thank you', 6),
('fr', 'é', 'ay', 'Closed "e", like "ay" without the glide', 'café', 'coffee', 7),
('fr', 'è/ê', 'eh', 'Open "e", like "e" in "bed"', 'très', 'very', 8),
('fr', 'ç', 's', 'Always a soft "s" sound', 'français', 'French', 9),
('fr', 'gn', 'ny', 'Like "ny" in "canyon"', 'montagne', 'mountain', 10),
-- Hindi (Devanagari core vowels + consonants)
('hi', 'अ', 'a', 'Short "a" as in "about"', 'अनार', 'pomegranate', 1),
('hi', 'आ', 'aa', 'Long "aa" as in "father"', 'आम', 'mango', 2),
('hi', 'इ', 'i', 'Short "i" as in "sit"', 'इमली', 'tamarind', 3),
('hi', 'ई', 'ee', 'Long "ee" as in "see"', 'ईख', 'sugarcane', 4),
('hi', 'उ', 'u', 'Short "u" as in "put"', 'उल्लू', 'owl', 5),
('hi', 'ऊ', 'oo', 'Long "oo" as in "food"', 'ऊन', 'wool', 6),
('hi', 'ए', 'e', 'Like "ay" in "say"', 'एक', 'one', 7),
('hi', 'ओ', 'o', 'Like "o" in "go"', 'ओस', 'dew', 8),
('hi', 'क', 'ka', 'Unaspirated "k"', 'कमल', 'lotus', 9),
('hi', 'ख', 'kha', 'Aspirated "k" — with a puff of breath', 'खरगोश', 'rabbit', 10),
('hi', 'ग', 'ga', 'Hard "g" as in "go"', 'गाय', 'cow', 11),
('hi', 'च', 'cha', 'Like "ch" in "chair"', 'चाय', 'tea', 12),
('hi', 'त', 'ta', 'Dental "t" — tongue touches teeth', 'तारा', 'star', 13),
('hi', 'न', 'na', 'Like English "n"', 'नमक', 'salt', 14),
('hi', 'म', 'ma', 'Like English "m"', 'मछली', 'fish', 15),
-- Japanese (hiragana, gojūon a-line through k/s-line)
('ja', 'あ', 'a', 'Short "a" as in "father"', 'あさ', 'morning', 1),
('ja', 'い', 'i', 'Short "i" as in "see"', 'いぬ', 'dog', 2),
('ja', 'う', 'u', 'Short "u", lips not rounded', 'うみ', 'sea', 3),
('ja', 'え', 'e', 'Like "e" in "bed"', 'えき', 'station', 4),
('ja', 'お', 'o', 'Like "o" in "go"', 'おちゃ', 'tea', 5),
('ja', 'か', 'ka', 'Like "ka" in "car"', 'かさ', 'umbrella', 6),
('ja', 'き', 'ki', 'Like "key"', 'きた', 'north', 7),
('ja', 'く', 'ku', 'Like "coo" (unrounded)', 'くも', 'cloud/spider', 8),
('ja', 'さ', 'sa', 'Like "sa" in "sun"', 'さかな', 'fish', 9),
('ja', 'し', 'shi', 'Like "she"', 'しお', 'salt', 10),
('ja', 'す', 'su', 'Like "su" (unrounded)', 'すし', 'sushi', 11),
('ja', 'そ', 'so', 'Like "so"', 'そら', 'sky', 12),
('ja', 'た', 'ta', 'Like "ta" in "tap"', 'たまご', 'egg', 13),
('ja', 'な', 'na', 'Like English "na"', 'なつ', 'summer', 14),
('ja', 'は', 'ha', 'Like English "ha"', 'はな', 'flower', 15);

-- ===== Essential survival phrases =====

insert into survival_phrases (language, category, phrase, translation, pronunciation, order_index) values
-- German
('de', 'greetings', 'Hallo', 'Hello', 'HAH-loh', 1),
('de', 'greetings', 'Guten Morgen', 'Good morning', 'GOO-ten MOR-gen', 2),
('de', 'greetings', 'Auf Wiedersehen', 'Goodbye', 'owf VEE-der-zayn', 3),
('de', 'essentials', 'Bitte', 'Please', 'BIT-teh', 4),
('de', 'essentials', 'Danke', 'Thank you', 'DAHN-keh', 5),
('de', 'essentials', 'Ja / Nein', 'Yes / No', 'yah / nine', 6),
('de', 'essentials', 'Entschuldigung', 'Excuse me / Sorry', 'ent-SHOOL-dee-goong', 7),
('de', 'essentials', 'Ich verstehe nicht', 'I don''t understand', 'ikh fer-SHTAY-eh nikht', 8),
('de', 'essentials', 'Sprechen Sie Englisch?', 'Do you speak English?', 'SHPREKH-en zee ENG-lish', 9),
('de', 'emergency', 'Hilfe!', 'Help!', 'HIL-feh', 10),
('de', 'emergency', 'Ruf einen Krankenwagen!', 'Call an ambulance!', 'roof EYE-nen KRAHN-ken-vah-gen', 11),
('de', 'dining', 'Die Rechnung, bitte', 'The bill, please', 'dee REKH-noong BIT-teh', 12),
('de', 'directions', 'Wo ist die Toilette?', 'Where is the bathroom?', 'voh ist dee toy-LET-eh', 13),
('de', 'directions', 'Wie viel kostet das?', 'How much does this cost?', 'vee feel KOS-tet dahs', 14),
-- Spanish
('es', 'greetings', 'Hola', 'Hello', 'OH-lah', 1),
('es', 'greetings', 'Buenos días', 'Good morning', 'BWAY-nos DEE-ahs', 2),
('es', 'greetings', 'Adiós', 'Goodbye', 'ah-DYOS', 3),
('es', 'essentials', 'Por favor', 'Please', 'por fah-VOR', 4),
('es', 'essentials', 'Gracias', 'Thank you', 'GRAH-syahs', 5),
('es', 'essentials', 'Sí / No', 'Yes / No', 'see / no', 6),
('es', 'essentials', 'Perdón / Lo siento', 'Excuse me / Sorry', 'per-DOHN / lo SYEN-toh', 7),
('es', 'essentials', 'No entiendo', 'I don''t understand', 'no en-TYEN-doh', 8),
('es', 'essentials', '¿Hablas inglés?', 'Do you speak English?', 'AH-blahs een-GLES', 9),
('es', 'emergency', '¡Ayuda!', 'Help!', 'ah-YOO-dah', 10),
('es', 'emergency', 'Llama una ambulancia', 'Call an ambulance', 'YAH-mah OO-nah ahm-boo-LAHN-syah', 11),
('es', 'dining', 'La cuenta, por favor', 'The bill, please', 'lah KWEN-tah por fah-VOR', 12),
('es', 'directions', '¿Dónde está el baño?', 'Where is the bathroom?', 'DOHN-deh es-TAH el BAH-nyoh', 13),
('es', 'directions', '¿Cuánto cuesta esto?', 'How much does this cost?', 'KWAHN-toh KWES-tah ES-toh', 14),
-- French
('fr', 'greetings', 'Bonjour', 'Hello', 'bohn-ZHOOR', 1),
('fr', 'greetings', 'Bonsoir', 'Good evening', 'bohn-SWAHR', 2),
('fr', 'greetings', 'Au revoir', 'Goodbye', 'oh reh-VWAHR', 3),
('fr', 'essentials', 'S''il vous plaît', 'Please', 'seel voo PLEH', 4),
('fr', 'essentials', 'Merci', 'Thank you', 'mehr-SEE', 5),
('fr', 'essentials', 'Oui / Non', 'Yes / No', 'wee / nohn', 6),
('fr', 'essentials', 'Excusez-moi / Pardon', 'Excuse me / Sorry', 'ex-koo-zay MWAH / par-DOHN', 7),
('fr', 'essentials', 'Je ne comprends pas', 'I don''t understand', 'zhuh nuh kohm-PRAHN pah', 8),
('fr', 'essentials', 'Parlez-vous anglais?', 'Do you speak English?', 'par-lay voo ahn-GLEH', 9),
('fr', 'emergency', 'Au secours!', 'Help!', 'oh suh-KOOR', 10),
('fr', 'emergency', 'Appelez une ambulance', 'Call an ambulance', 'ah-play oon ahm-boo-LAHNS', 11),
('fr', 'dining', 'L''addition, s''il vous plaît', 'The bill, please', 'lah-dee-SYOHN seel voo PLEH', 12),
('fr', 'directions', 'Où sont les toilettes?', 'Where is the bathroom?', 'oo sohn lay twah-LET', 13),
('fr', 'directions', 'Combien ça coûte?', 'How much does this cost?', 'kohm-byahn sah KOOT', 14),
-- Hindi
('hi', 'greetings', 'नमस्ते', 'Hello', 'nuh-muh-STAY', 1),
('hi', 'greetings', 'शुभ प्रभात', 'Good morning', 'shoobh pruh-BHAHT', 2),
('hi', 'greetings', 'अलविदा', 'Goodbye', 'uhl-vih-DAH', 3),
('hi', 'essentials', 'कृपया', 'Please', 'krip-YAH', 4),
('hi', 'essentials', 'धन्यवाद', 'Thank you', 'dhun-yuh-VAHD', 5),
('hi', 'essentials', 'हाँ / नहीं', 'Yes / No', 'haan / nuh-HEEN', 6),
('hi', 'essentials', 'माफ़ कीजिए', 'Excuse me / Sorry', 'maaf KEE-jee-eh', 7),
('hi', 'essentials', 'मुझे समझ नहीं आया', 'I don''t understand', 'moo-jheh suh-MUJH nuh-HEEN aa-YAH', 8),
('hi', 'essentials', 'क्या आप अंग्रेज़ी बोलते हैं?', 'Do you speak English?', 'kyaa aap un-gray-ZEE bol-teh hain', 9),
('hi', 'emergency', 'बचाओ!', 'Help!', 'buh-CHAH-oh', 10),
('hi', 'emergency', 'एम्बुलेंस बुलाओ', 'Call an ambulance', 'am-boo-LENS boo-LAH-oh', 11),
('hi', 'dining', 'बिल दीजिए', 'The bill, please', 'bill DEE-jee-eh', 12),
('hi', 'directions', 'बाथरूम कहाँ है?', 'Where is the bathroom?', 'BATH-room kuh-HAAN hai', 13),
('hi', 'directions', 'यह कितने का है?', 'How much does this cost?', 'yeh KIT-neh kaa hai', 14),
-- Japanese
('ja', 'greetings', 'こんにちは', 'Hello', 'kon-nee-chee-wah', 1),
('ja', 'greetings', 'おはようございます', 'Good morning', 'oh-hah-yoh goh-zai-mahs', 2),
('ja', 'greetings', 'さようなら', 'Goodbye', 'sah-yoh-nah-rah', 3),
('ja', 'essentials', 'お願いします', 'Please', 'oh-neh-gai shee-mahs', 4),
('ja', 'essentials', 'ありがとうございます', 'Thank you', 'ah-ree-gah-toh goh-zai-mahs', 5),
('ja', 'essentials', 'はい / いいえ', 'Yes / No', 'hai / ee-eh', 6),
('ja', 'essentials', 'すみません', 'Excuse me / Sorry', 'soo-mee-mah-sen', 7),
('ja', 'essentials', 'わかりません', 'I don''t understand', 'wah-kah-ree-mah-sen', 8),
('ja', 'essentials', '英語を話せますか?', 'Do you speak English?', 'ay-goh oh hah-nah-seh-mahs kah', 9),
('ja', 'emergency', '助けて!', 'Help!', 'tahs-keh-teh', 10),
('ja', 'emergency', '救急車を呼んでください', 'Call an ambulance', 'kyoo-kyoo-shah oh yon-deh koo-dah-sai', 11),
('ja', 'dining', 'お会計をお願いします', 'The bill, please', 'oh-kai-kay oh oh-neh-gai shee-mahs', 12),
('ja', 'directions', 'トイレはどこですか?', 'Where is the bathroom?', 'toy-reh wah doh-koh dess kah', 13),
('ja', 'directions', 'いくらですか?', 'How much does this cost?', 'ee-koo-rah dess kah', 14);
